name: .NET Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:
    inputs:
      releasePage:
        description: 'Release to GitHub Pages? (Y/N)'
        required: false
        default: 'N'


jobs:
  steps:   
  


  
    - name: Release to GitHub Pages
      if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event.inputs.releasePage == 'Y'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /home/runner/work/output/wwwroot
        cname: joshuapeddle.com
        force_orphan: true