name: .NET Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      releasePage:
        description: 'Release to GitHub Pages? (Y/N)'
        required: false
        default: 'N'


jobs:
  build-and-deploy:    
  - name: Build and Deploy Website
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Blog.Wasm/Blog.Wasm.csproj

    - name: Build project
      run: dotnet build Blog.Wasm/Blog.Wasm.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish Blog.Wasm/Blog.Wasm.csproj --configuration Release --no-build -o /home/runner/work/output

    - name: Release to GitHub Pages
      if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event.inputs.releasePage == 'Y'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /home/runner/work/output/wwwroot
        cname: joshuapeddle.com
        force_orphan: true